apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehr-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ehr-app
  template:
    metadata:
      labels:
        app: ehr-app
    spec:
      containers:
        - name: ehr-app
          image: ginger2000/pace-tech-app:38
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
